In [1]:
import pymongo
# from pymongo import MongoClient
import pandas as pd

In [2]:
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

# db
db = client.stack

# Declare the collection
lang_pct = db.lang_pct

In [5]:
test = db.percent.find()
for record in test:
    print(record)

In [4]:
test = db.salary.find()
for record in test:
    print(record)

{'_id': ObjectId('617cf9dc8e3c628a2c968d24'), 'index': '0', 'language': 'JavaScript', 'avg_salary': 114864.94013838634, 'survey_year': '2021'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d25'), 'index': '1', 'language': 'HTML/CSS', 'avg_salary': 113497.73098142823, 'survey_year': '2021'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d26'), 'index': '2', 'language': 'Python', 'avg_salary': 124533.7195079086, 'survey_year': '2021'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d27'), 'index': '3', 'language': 'SQL', 'avg_salary': 117631.4810222353, 'survey_year': '2021'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d28'), 'index': '4', 'language': 'Java', 'avg_salary': 115848.8901850362, 'survey_year': '2021'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d29'), 'index': '5', 'language': 'Node.js', 'avg_salary': 123406.11506416104, 'survey_year': '2021'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d2a'), 'index': '6', 'language': 'TypeScript', 'avg_salary': 127429.09154169168, 'survey_year': '2021'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d2b'), 'index': '7', 'language': 'C#', 'avg_salary': 123497.10245183887, 'survey_year': '2021'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d2c'), 'index': '8', 'language': 'Bash/Shell', 'avg_salary': 144981.97340231726, 'survey_year': '2021'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d2d'), 'index': '9', 'language': 'C++', 'avg_salary': 118030.1136444182, 'survey_year': '2021'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d2e'), 'index': '0', 'language': 'JavaScript', 'avg_salary': 102280.80469113847, 'survey_year': '2020'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d2f'), 'index': '1', 'language': 'HTML/CSS', 'avg_salary': 100018.7772516382, 'survey_year': '2020'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d30'), 'index': '2', 'language': 'SQL', 'avg_salary': 103281.52037228542, 'survey_year': '2020'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d31'), 'index': '3', 'language': 'Python', 'avg_salary': 113061.52551862752, 'survey_year': '2020'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d32'), 'index': '4', 'language': 'Java', 'avg_salary': 105150.55702746366, 'survey_year': '2020'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d33'), 'index': '5', 'language': 'Bash/Shell/PowerShell', 'avg_salary': 123621.34345533005, 'survey_year': '2020'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d34'), 'index': '6', 'language': 'C#', 'avg_salary': 107592.11212175792, 'survey_year': '2020'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d35'), 'index': '7', 'language': 'PHP', 'avg_salary': 81937.73262032085, 'survey_year': '2020'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d36'), 'index': '8', 'language': 'TypeScript', 'avg_salary': 107735.75537040755, 'survey_year': '2020'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d37'), 'index': '9', 'language': 'C++', 'avg_salary': 111340.13526266122, 'survey_year': '2020'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d38'), 'index': '0', 'language': 'JavaScript', 'avg_salary': 127492.88098593352, 'survey_year': '2019'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d39'), 'index': '1', 'language': 'HTML/CSS', 'avg_salary': 124628.0385097057, 'survey_year': '2019'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d3a'), 'index': '2', 'language': 'SQL', 'avg_salary': 128448.33660739665, 'survey_year': '2019'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d3b'), 'index': '3', 'language': 'Python', 'avg_salary': 141269.54417216746, 'survey_year': '2019'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d3c'), 'index': '4', 'language': 'Java', 'avg_salary': 121979.8656046138, 'survey_year': '2019'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d3d'), 'index': '5', 'language': 'Bash/Shell/PowerShell', 'avg_salary': 147670.7298919018, 'survey_year': '2019'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d3e'), 'index': '6', 'language': 'C#', 'avg_salary': 131545.5018270402, 'survey_year': '2019'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d3f'), 'index': '7', 'language': 'PHP', 'avg_salary': 102961.4537263947, 'survey_year': '2019'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d40'), 'index': '8', 'language': 'C++', 'avg_salary': 129104.95508982036, 'survey_year': '2019'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d41'), 'index': '9', 'language': 'TypeScript', 'avg_salary': 133337.36770213704, 'survey_year': '2019'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d42'), 'index': '0', 'language': 'JavaScript', 'avg_salary': 97974.17145899891, 'survey_year': '2018'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d43'), 'index': '1', 'language': 'HTML', 'avg_salary': 95030.69808103668, 'survey_year': '2018'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d44'), 'index': '2', 'language': 'CSS', 'avg_salary': 95604.4886275272, 'survey_year': '2018'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d45'), 'index': '3', 'language': 'SQL', 'avg_salary': 97567.42716457607, 'survey_year': '2018'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d46'), 'index': '4', 'language': 'Java', 'avg_salary': 90282.98584624552, 'survey_year': '2018'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d47'), 'index': '5', 'language': 'Bash/Shell', 'avg_salary': 107340.89994119952, 'survey_year': '2018'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d48'), 'index': '6', 'language': 'Python', 'avg_salary': 101955.64278257047, 'survey_year': '2018'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d49'), 'index': '7', 'language': 'C#', 'avg_salary': 99185.49439274636, 'survey_year': '2018'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d4a'), 'index': '8', 'language': 'PHP', 'avg_salary': 81961.01156661786, 'survey_year': '2018'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d4b'), 'index': '9', 'language': 'C++', 'avg_salary': 90378.2715313269, 'survey_year': '2018'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d4c'), 'index': '0', 'language': 'JavaScript', 'avg_salary': 56396.92270639816, 'survey_year': '2017'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d4d'), 'index': '1', 'language': 'SQL', 'avg_salary': 55663.30820719875, 'survey_year': '2017'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d4e'), 'index': '2', 'language': 'Java', 'avg_salary': 55184.95040948789, 'survey_year': '2017'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d4f'), 'index': '3', 'language': 'C#', 'avg_salary': 58305.49989463399, 'survey_year': '2017'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d50'), 'index': '4', 'language': 'Python', 'avg_salary': 61641.073323707606, 'survey_year': '2017'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d51'), 'index': '5', 'language': 'PHP', 'avg_salary': 44780.66485359173, 'survey_year': '2017'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d52'), 'index': '6', 'language': 'C++', 'avg_salary': 58690.2627537448, 'survey_year': '2017'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d53'), 'index': '7', 'language': 'C', 'avg_salary': 56663.80076973501, 'survey_year': '2017'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d54'), 'index': '8', 'language': 'TypeScript', 'avg_salary': 59623.00895134647, 'survey_year': '2017'}
{'_id': ObjectId('617cf9dc8e3c628a2c968d55'), 'index': '9', 'language': 'Ruby', 'avg_salary': 65581.2616907475, 'survey_year': '2017'}

In [6]:
pct_one = "clean_data/language_percent_2021.csv"
pct_one_df = pd.read_csv(pct_one, encoding="ISO-8859-1")
pct_one_df

    Unnamed: 0     language  percentage  survey_year
0            0   JavaScript   64.222965         2021
1            1     HTML/CSS   55.440501         2021
2            2       Python   47.689929         2021
3            3          SQL   46.542983         2021
4            4         Java   34.950083         2021
5            5      Node.js   33.527487         2021
6            6   TypeScript   29.852946         2021
7            7           C#   27.545872         2021
8            8   Bash/Shell   26.827982         2021
9            9          C++   24.037920         2021
10          10          PHP   21.728448         2021
11          11            C   20.768466         2021
12          12   PowerShell   10.631719         2021
13          13           Go    9.442826         2021
14          14       Kotlin    8.228766         2021
15          15         Rust    6.949987         2021
16          16         Ruby    6.674337         2021
17          17         Dart    5.950455         2021
18          18     Assembly    5.551361         2021
19          19        Swift    5.038411         2021
20          20            R    5.015640         2021
21          21          VBA    4.610554         2021
22          22       Matlab    4.609355         2021
23          23       Groovy    2.971033         2021
24          24  Objective-C    2.768490         2021
25          25        Scala    2.574336         2021
26          26         Perl    2.430518         2021
27          27      Haskell    2.096142         2021
28          28       Delphi    2.074569         2021
29          29      Clojure    1.860041         2021
30          30       Elixir    1.723415         2021
31          31         LISP    1.313534         2021
32          32        Julia    1.279977         2021
33          33           F#    0.963578         2021
34          34       Erlang    0.780211         2021
35          35          APL    0.642385         2021
36          36      Crystal    0.558492         2021
37          37        COBOL    0.523736         2021

In [7]:
pct_two = "clean_data/language_percent_2020.csv"
pct_two_df = pd.read_csv(pct_two, encoding="ISO-8859-1")
pct_two_df

    Unnamed: 0               language  percentage  survey_year
0            0             JavaScript   60.225563         2020
1            1               HTML/CSS   56.128512         2020
2            2                    SQL   48.731791         2020
3            3                 Python   39.228371         2020
4            4                   Java   35.795287         2020
5            5  Bash/Shell/PowerShell   29.444160         2020
6            6                     C#   27.987465         2020
7            7                    PHP   23.280743         2020
8            8             TypeScript   22.615225         2020
9            9                    C++   21.264020         2020
10          10                      C   19.371403         2020
11          11                     Go    7.815578         2020
12          12                 Kotlin    6.931323         2020
13          13                   Ruby    6.276663         2020
14          14               Assembly    5.511860         2020
15          15                    VBA    5.428088         2020
16          16                  Swift    5.269853         2020
17          17                      R    5.100759         2020
18          18                   Rust    4.543833         2020
19          19            Objective-C    3.630102         2020
20          20                   Dart    3.537022         2020
21          21                  Scala    3.183320         2020
22          22                   Perl    2.786181         2020
23          23                Haskell    1.895720         2020
24          24                  Julia    0.805138         2020

In [8]:
pct_three = "clean_data/language_percent_2019.csv"
pct_three_df = pd.read_csv(pct_three, encoding="ISO-8859-1")
pct_three_df

    Unnamed: 0               language  percentage  survey_year
0            0             JavaScript   66.625789         2019
1            1               HTML/CSS   62.403384         2019
2            2                    SQL   53.490544         2019
3            3                 Python   41.001091         2019
4            4                   Java   40.409302         2019
5            5  Bash/Shell/PowerShell   35.992259         2019
6            6                     C#   30.486145         2019
7            7                    PHP   25.910467         2019
8            8                    C++   23.091030         2019
9            9             TypeScript   20.839756         2019
10          10                      C   20.270468         2019
11          11              Other(s):    8.910590         2019
12          12                   Ruby    8.247921         2019
13          13                     Go    8.101662         2019
14          14               Assembly    6.562560         2019
15          15                  Swift    6.462428         2019
16          16                 Kotlin    6.322919         2019
17          17                      R    5.679376         2019
18          18                    VBA    5.378981         2019
19          19            Objective-C    4.715187         2019
20          20                  Scala    3.722872         2019
21          21                   Rust    3.143458         2019
22          22                   Dart    1.893500         2019
23          23                 Elixir    1.417594         2019
24          24                Clojure    1.410843         2019
25          25            WebAssembly    1.141951         2019
26          26                     F#    1.094698         2019
27          27                 Erlang    0.874183         2019

In [9]:
pct_four = "clean_data/language_percent_2018.csv"
pct_four_df = pd.read_csv(pct_four, encoding="ISO-8859-1")
pct_four_df

    Unnamed: 0              language  percentage  survey_year
0            0            JavaScript   55.319407         2018
1            1                  HTML   54.249153         2018
2            2                   CSS   51.569470         2018
3            3                   SQL   45.187396         2018
4            4                  Java   35.932426         2018
5            5            Bash/Shell   31.533053         2018
6            6                Python   30.710637         2018
7            7                    C#   27.266198         2018
8            8                   PHP   24.349805         2018
9            9                   C++   20.102170         2018
10          10                     C   18.250974         2018
11          11            TypeScript   13.783825         2018
12          12                  Ruby    8.002630         2018
13          13                 Swift    6.383086         2018
14          14              Assembly    5.826716         2018
15          15                    Go    5.596075         2018
16          16           Objective-C    5.573820         2018
17          17                VB.NET    5.314855         2018
18          18                     R    4.868747         2018
19          19                Matlab    4.616863         2018
20          20                   VBA    3.854130         2018
21          21                Kotlin    3.548632         2018
22          22                 Scala    3.459613         2018
23          23                Groovy    3.412068         2018
24          24                  Perl    3.317991         2018
25          25        Visual Basic 6    3.122756         2018
26          26                   Lua    2.764655         2018
27          27          CoffeeScript    2.633150         2018
28          28  Delphi/Object Pascal    2.048455         2018
29          29               Haskell    1.983714         2018
30          30                  Rust    1.878509         2018
31          31                    F#    1.127915         2018
32          32               Clojure    1.043953         2018
33          33                Erlang    0.896262         2018
34          34                 Cobol    0.596834         2018
35          35                 Ocaml    0.475444         2018
36          36                 Julia    0.434981         2018
37          37                  Hack    0.256942         2018

In [10]:
pct_five = "clean_data/language_percent_2017.csv"
pct_five_df = pd.read_csv(pct_five, encoding="ISO-8859-1")
pct_five_df

    Unnamed: 0      language  percentage  survey_year
0            0    JavaScript   44.510819         2017
1            1           SQL   36.492061         2017
2            2          Java   28.261208         2017
3            3            C#   24.276152         2017
4            4        Python   22.773973         2017
5            5           PHP   20.022572         2017
6            6           C++   15.868229         2017
7            7             C   13.570205         2017
8            8    TypeScript    6.787049         2017
9            9          Ruby    6.467933         2017
10          10         Swift    4.607721         2017
11          11   Objective-C    4.570750         2017
12          12        VB.NET    4.422867         2017
13          13      Assembly    3.547245         2017
14          14             R    3.179483         2017
15          15          Perl    3.084138         2017
16          16           VBA    3.062733         2017
17          17        Matlab    3.053004         2017
18          18            Go    3.029654         2017
19          19         Scala    2.547089         2017
20          20        Groovy    2.321373         2017
21          21  CoffeeScript    2.319427         2017
22          22  VisualBasic6    2.083982         2017
23          23           Lua    2.021715         2017
24          24       Haskell    1.262842         2017
25          25            F#    0.889243         2017
26          26          Rust    0.809465         2017
27          27       Clojure    0.760819         2017
28          28        Elixir    0.739415         2017
29          29     Smalltalk    0.636286         2017
30          30        Erlang    0.546778         2017
31          31    CommonLisp    0.531211         2017
32          32          Dart    0.282145         2017
33          33         Julia    0.268524         2017
34          34          Hack    0.208204         2017

In [12]:
pct_six = "clean_data/language_percent_2016.csv"
pct_six_df = pd.read_csv(pct_six, encoding="ISO-8859-1")
pct_six_df['survey_year']='2016'
pct_six_df

    Unnamed: 0                   language  percentage survey_year
0            0                 JavaScript   56.482749        2016
1            1                        SQL   45.235676        2016
2            2                       Java   36.206211        2016
3            3                         C#   31.388877        2016
4            4                        PHP   26.200468        2016
5            5                     Python   24.892874        2016
6            6                  SQLServer   19.293634        2016
7            7                        C++   19.083801        2016
8            8                  AngularJS   18.394664        2016
9            9                    Node.js   17.659142        2016
10          10                    Android   17.413968        2016
11          11                          C   15.216239        2016
12          12                       LAMP   10.052127        2016
13          13                    MongoDB    9.935062        2016
14          14  Cloud(AWS,GAE,Azure,etc.)    9.767195        2016
15          15                        iOS    9.398330        2016
16          16                  WordPress    9.349737        2016
17          17                       Ruby    9.188497        2016
18          18        Arduino/RaspberryPi    7.710827        2016
19          19                VisualBasic    6.798604        2016
20          20                Objective-C    6.730132        2016
21          21                      Redis    6.032160        2016
22          22                      Swift    5.769316        2016
23          23                    ReactJS    5.336396        2016
24          24               CoffeeScript    3.505323        2016
25          25                    Cordova    3.419181        2016
26          26                      Scala    3.330830        2016
27          27                          R    3.319786        2016
28          28                       Perl    3.304325        2016
29          29                         Go    3.198304        2016
30          30                     Matlab    3.187260        2016
31          31               WindowsPhone    2.314794        2016
32          32                     Hadoop    2.080664        2016
33          33                 SharePoint    1.797941        2016
34          34                    Haskell    1.621240        2016
35          35                      Spark    1.462208        2016
36          36                 Salesforce    1.378275        2016
37          37                  Cassandra    1.376066        2016
38          38                    Clojure    1.155188        2016
39          39                         F#    1.013827        2016
40          40                       Rust    0.896762        2016
41          41                       Dart    0.450590        2016

In [13]:
pct_seven = "clean_data/language_percent_2015.csv"
pct_seven_df = pd.read_csv(pct_seven, encoding="ISO-8859-1")
pct_seven_df

FileNotFoundError: [Errno 2] No such file or directory: 'clean_data/language_percent_2015.csv'

In [14]:
pct_eight = "clean_data/language_percent_2014.csv"
pct_eight_df = pd.read_csv(pct_eight, encoding="ISO-8859-1")
pct_eight_df['survey_year']='2014'
pct_eight_df

    Unnamed: 0     language  percentage survey_year
0            0   JavaScript   49.496271        2014
1            1          SQL   45.361769        2014
2            2         Java   32.434908        2014
3            3           C#   31.113437        2014
4            4          PHP   22.373414        2014
5            5       Python   19.272537        2014
6            6          C++   18.552924        2014
7            7            C   15.360461        2014
8            8  Objective-C    8.831611        2014
9            9      Node.js    8.386759        2014
10          10         Ruby    7.758733        2014

In [15]:
pct_nine = "clean_data/language_percent_2013.csv"
pct_nine_df = pd.read_csv(pct_nine, encoding="ISO-8859-1")
pct_nine_df['survey_year']='2013'
pct_nine_df

    Unnamed: 0     language  percentage survey_year
0            0   JavaScript   48.603983        2013
1            1          SQL   47.146377        2013
2            2       jQuery   42.178197        2013
3            3           C#   31.071649        2013
4            4         Java   30.999795        2013
5            5          PHP   23.855471        2013
6            6       Python   19.297885        2013
7            7          C++   17.409156        2013
8            8            C   14.740300        2013
9            9  Objective-C    9.802915        2013
10          10         Ruby    8.150277        2013
11          11      Node.js    6.148635        2013
12          12       JQuery    2.453295        2013

In [16]:
pct_ten = "clean_data/language_percent_2012.csv"
pct_ten_df = pd.read_csv(pct_ten, encoding="ISO-8859-1")
pct_ten_df['survey_year']='2012'
pct_ten_df

    Unnamed: 0     language  percentage survey_year
0            0          SQL   52.763095        2012
1            1   JavaScript   50.088099        2012
2            2          CSS   45.234663        2012
3            3           C#   39.532276        2012
4            4         Java   37.610123        2012
5            5        HTML5   34.502643        2012
6            6          PHP   30.834535        2012
7            7          C++   24.443377        2012
8            8            C   23.770623        2012
9            9       Python   19.381708        2012
10          10  Objective-C    9.690854        2012
11          11         Ruby    9.242351        2012
12          12         Perl    7.384270        2012
13          13         None    0.080090        2012

In [17]:
pct_eleven = "clean_data/language_percent_2011.csv"
pct_eleven_df = pd.read_csv(pct_eleven, encoding="ISO-8859-1")
pct_eleven_df['survey_year']='2011'
pct_eleven_df

    Unnamed: 0    language  percentage survey_year
0            0         SQL   57.340917        2011
1            1  JavaScript   50.444365        2011
2            2         CSS   48.204764        2011
3            3          C#   48.062567        2011
4            4        Java   30.607892        2011
5            5         PHP   28.012798        2011
6            6           C   26.341984        2011
7            7         C++   26.306434        2011
8            8      Python   20.440811        2011
9            9        Ruby   10.131532        2011
10          10        Perl   10.095983        2011

In [18]:
frames = [pct_one_df, pct_two_df, pct_three_df, pct_four_df, pct_five_df, pct_six_df, pct_eight_df, pct_nine_df, pct_ten_df,pct_eleven_df]

pct_df = pd.concat(frames)
pct_df

    Unnamed: 0    language  percentage survey_year
0            0  JavaScript   64.222965        2021
1            1    HTML/CSS   55.440501        2021
2            2      Python   47.689929        2021
3            3         SQL   46.542983        2021
4            4        Java   34.950083        2021
..         ...         ...         ...         ...
6            6           C   26.341984        2011
7            7         C++   26.306434        2011
8            8      Python   20.440811        2011
9            9        Ruby   10.131532        2011
10          10        Perl   10.095983        2011

[255 rows x 4 columns]

In [19]:
pct_df.columns

Index(['Unnamed: 0', 'language', 'percentage', 'survey_year'], dtype='object')

In [20]:
pct_df.drop('Unnamed: 0', axis=1, inplace=True)
pct_df = pct_df.reset_index()
pct_df

     index    language  percentage survey_year
0        0  JavaScript   64.222965        2021
1        1    HTML/CSS   55.440501        2021
2        2      Python   47.689929        2021
3        3         SQL   46.542983        2021
4        4        Java   34.950083        2021
..     ...         ...         ...         ...
250      6           C   26.341984        2011
251      7         C++   26.306434        2011
252      8      Python   20.440811        2011
253      9        Ruby   10.131532        2011
254     10        Perl   10.095983        2011

[255 rows x 4 columns]

In [21]:
# use this to poppulate mongo 'percent' collection
pct_df.to_csv("clean_data/pct_df.csv", index=False, header=True)

In [28]:
lang_pct.insert_one(pct_df.to_dict('language'))

C:\Users\u00rxv9\Anaconda3\lib\site-packages\pandas\core\frame.py:1549: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  warnings.warn(

In [29]:
test = db.lang_pct.find()
for record in test:
    print(record)

{'_id': ObjectId('61796abd01d1893f0e12aae9'), 'Unnamed: 0': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'language': ['JavaScript', 'HTML/CSS', 'Python', 'SQL', 'Java', 'Node.js', 'TypeScript', 'C#', 'Bash/Shell', 'C++', 'PHP', 'C', 'PowerShell', 'Go', 'Kotlin', 'Rust', 'Ruby', 'Dart', 'Assembly', 'Swift', 'R', 'VBA', 'Matlab', 'Groovy', 'Objective-C', 'Scala', 'Perl', 'Haskell', 'Delphi', 'Clojure', 'Elixir', 'LISP', 'Julia', 'F#', 'Erlang', 'APL', 'Crystal', 'COBOL', 'JavaScript', 'HTML/CSS', 'SQL', 'Python', 'Java', 'Bash/Shell/PowerShell', 'C#', 'PHP', 'TypeScript', 'C++', 'C', 'Go', 'Kotlin', 'Ruby', 'Assembly', 'VBA', 'Swift', 'R', 'Rust', 'Objective-C', 'Dart', 'Scala', 'Perl', 'Haskell', 'Julia', 'JavaScript', 'HTML/CSS', 'SQL', 'Python', 'Java', 'Bash/Shell/PowerShell', 'C#', 'PHP', 'C++', 'TypeScript', 'C', 'Other(s):', 'Ruby', 'Go', 'Assembly', 'Swift', 'Kotlin', 'R', 'VBA', 'Objective-C', 'Scala', 'Rust', 'Dart', 'Elixir', 'Clojure', 'WebAssembly', 'F#', 'Erlang', 'JavaScript', 'HTML', 'CSS', 'SQL', 'Java', 'Bash/Shell', 'Python', 'C#', 'PHP', 'C++', 'C', 'TypeScript', 'Ruby', 'Swift', 'Assembly', 'Go', 'Objective-C', 'VB.NET', 'R', 'Matlab', 'VBA', 'Kotlin', 'Scala', 'Groovy', 'Perl', 'Visual Basic 6', 'Lua', 'CoffeeScript', 'Delphi/Object Pascal', 'Haskell', 'Rust', 'F#', 'Clojure', 'Erlang', 'Cobol', 'Ocaml', 'Julia', 'Hack', ' SQL', ' JavaScript', ' Python', ' PHP', ' Java', 'C#', 'Java', 'JavaScript', 'C', ' C++', ' C#', 'C++', ' TypeScript', ' Ruby', ' Swift', ' VB.NET', ' Objective-C', 'Assembly', ' VBA', ' R', ' Perl', ' Matlab', ' C', ' Scala', ' Visual Basic 6', ' Lua', ' Go', 'Python', 'CoffeeScript', 'Groovy', ' Groovy', 'Go', ' Haskell', 'PHP', ' CoffeeScript', ' F#', ' Rust', 'Objective-C', 'SQL', ' Smalltalk', ' Erlang', ' Common Lisp', ' Elixir', ' Clojure', 'Clojure', 'Elixir', 'R', 'Ruby', 'Perl', 'Matlab', 'Haskell', ' Julia', ' Dart', ' Hack', 'Swift', 'Smalltalk', 'Erlang', 'Scala', 'Common Lisp', 'Lua', 'Dart', 'VB.NET', 'Julia', 'VBA', 'F#', 'Hack', 'TypeScript', 'Visual Basic 6', 'Rust', 'JavaScript', 'SQL', 'Java', 'C#', 'PHP', 'Python', 'SQLServer', 'C++', 'AngularJS', 'Node.js', 'Android', 'C', 'LAMP', 'MongoDB', 'Cloud(AWS,GAE,Azure,etc.)', 'iOS', 'WordPress', 'Ruby', 'Arduino/RaspberryPi', 'VisualBasic', 'Objective-C', 'Redis', 'Swift', 'ReactJS', 'CoffeeScript', 'Cordova', 'Scala', 'R', 'Perl', 'Go', 'Matlab', 'WindowsPhone', 'Hadoop', 'SharePoint', 'Haskell', 'Spark', 'Salesforce', 'Cassandra', 'Clojure', 'F#', 'Rust', 'Dart', 'JavaScript', 'SQL', 'Java', 'C#', 'PHP', 'Python', 'C++', 'C', 'Objective-C', 'Node.js', 'Ruby', 'JavaScript', 'SQL', 'jQuery', 'C#', 'Java', 'PHP', 'Python', 'C++', 'C', 'Objective-C', 'Ruby', 'Node.js', 'JQuery', 'SQL', 'JavaScript', 'CSS', 'C#', 'Java', 'HTML5', 'PHP', 'C++', 'C', 'Python', 'Objective-C', 'Ruby', 'Perl', 'None', 'SQL', 'JavaScript', 'CSS', 'C#', 'Java', 'PHP', 'C', 'C++', 'Python', 'Ruby', 'Perl'], 'percentage': [64.22296528002492, 55.4405014441688, 47.68992916981268, 46.5429834969259, 34.95008329438272, 33.5274871462985, 29.8529464638838, 27.54587183451384, 26.82798211867352, 24.037919917544556, 21.728448327520702, 20.76846558563741, 10.631718980332938, 9.442826496003068, 8.228765924807345, 6.949987415956567, 6.674336940759118, 5.950454823284076, 5.551360874411246, 5.038411294478601, 5.015640168266637, 4.610553817759081, 4.609355337432136, 2.9710327304977286, 2.768489555243951, 2.5743357422787905, 2.4305181030453387, 2.096142091827563, 2.074569445942545, 1.8600414674193124, 1.723414710147533, 1.3135344383321947, 1.2799769891777226, 0.9635781828641284, 0.780210692841477, 0.6423854552427521, 0.5584918323565718, 0.5237359028751544, 60.2255627433642, 56.1285118133445, 48.731791315679246, 39.2283706427142, 35.79528707280371, 29.444160034749693, 27.987465289089524, 23.280743395231223, 22.61522470951428, 21.26402010517988, 19.371402863747072, 7.815578411752842, 6.9313228153457125, 6.27666340888289, 5.511859884271109, 5.428088301453593, 5.269853089464948, 5.100758598222181, 4.543832705046462, 3.630101922092429, 3.53702238562852, 3.183320147065668, 2.786180791486325, 1.895719892648268, 0.8051379904128078, 66.62578895851851, 62.40338422420485, 53.49054374852334, 41.001091322300105, 40.4093021162652, 35.99225948719103, 30.486144707086844, 25.91046656841016, 23.091029780722973, 20.83975563381074, 20.2704679184996, 8.910590326609139, 8.247921424794393, 8.10166173508995, 6.562559769584735, 6.462428135864001, 6.322918893376686, 5.679376258677137, 5.378981357514936, 4.715187381164002, 3.7228716402461663, 3.1434582541093348, 1.8935004444044417, 1.4175939155969084, 1.41084346837978, 1.1419506542308429, 1.0946975237109458, 0.8741829146180935, 55.319407212584096, 54.2491527995549, 51.5694704364979, 45.18739568054221, 35.932426280916495, 31.53305346214152, 30.71063679125993, 27.26619796671893, 24.349805270345456, 20.102169844722063, 18.250973648272723, 13.78382479389004, 8.002630114814629, 6.383086338576703, 5.826715897020889, 5.596075059430479, 5.573820241768247, 5.31485509078954, 4.868747154923878, 4.616863082292246, 3.854129786050276, 3.548631834505083, 3.459612563856153, 3.412068180668656, 3.317990996914673, 3.1227555510596328, 2.7646553032218906, 2.633149562490517, 2.048454807546406, 1.98371351980173, 1.8785089272166304, 1.1279146224267866, 1.0439532648829093, 0.8962622022153659, 0.5968337463962369, 0.4754438318749683, 0.4349805270345455, 0.256941985736685, 35.93166251556663, 33.388465130759656, 20.85733188044832, 19.00101183063512, 16.7769302615193, 16.726338729763388, 11.484277708592778, 11.122353673723536, 10.82464196762142, 9.005292652552926, 7.549813200498131, 6.862935865504359, 6.769536114570361, 6.176058530510585, 4.467621419676214, 4.35865504358655, 3.977272727272727, 3.547244707347448, 3.008250311332503, 2.883717310087173, 2.821450809464508, 2.794209215442092, 2.745563511830635, 2.453689290161893, 2.068415317559153, 1.94777397260274, 1.941936488169365, 1.9166407222914077, 1.3581880448318806, 1.175280199252802, 1.146092777085928, 1.087717932752179, 1.0429638854296388, 1.0215597758405977, 0.961239103362391, 0.8425435865504359, 0.801681195516812, 0.5934775840597759, 0.5603985056039851, 0.5020236612702367, 0.4514321295143212, 0.4378113325031133, 0.4339196762141967, 0.4164072229140722, 0.3444115815691158, 0.3054950186799502, 0.2957658779576588, 0.2918742216687422, 0.262686799501868, 0.2587951432129514, 0.2198785803237858, 0.2140410958904109, 0.2101494396014944, 0.1653953922789539, 0.1400996264009962, 0.1342621419676214, 0.0953455790784558, 0.0933997509339975, 0.0933997509339975, 0.0739414694894147, 0.0719956413449564, 0.0642123287671232, 0.0544831880448318, 0.0544831880448318, 0.0466998754669987, 0.0428082191780821, 0.0175124533001245, 0.0155666251556662, 0.0077833125778331, 56.48274948093829, 45.23567610549101, 36.20621107037152, 31.388876617926403, 26.200468259928435, 24.892874497504085, 19.29363431550117, 19.08380085700402, 18.39466360383443, 17.659142112470732, 17.413968282016167, 15.216238900914432, 10.052127048637187, 9.93506206652825, 9.76719529973053, 9.398330167425012, 9.349737155983568, 9.18849670892786, 7.710827406458454, 6.798604055307682, 6.73013208464019, 6.032159738481248, 5.769315722047975, 5.336396165569643, 3.505323143526086, 3.419180986879887, 3.3308300569863496, 3.319786190749657, 3.3043247780182887, 3.198303662146044, 3.1872597959093523, 2.3147943632106727, 2.0806643989927998, 1.7979414233334805, 1.6212395635464063, 1.4622078897380395, 1.3782745063391793, 1.3760657330918409, 1.155188408357998, 1.0138269205283386, 0.8967619384194018, 0.4505897424570393, 49.49627109773649, 45.36176893889834, 32.43490775873348, 31.113437132016227, 22.37341358105456, 19.272536961925944, 18.552924244406647, 15.360460552139212, 8.831610624100485, 8.386759125997646, 7.758733481617167, 48.60398275508109, 47.14637651406282, 42.17819749538083, 31.07164853212893, 30.999794703346332, 23.85547115582016, 19.29788544446725, 17.40915623075344, 14.740299733114352, 9.802915212482038, 8.150277150482447, 6.148634777253131, 2.453295011291316, 52.76309466602594, 50.08809867051097, 45.234662822361045, 39.532276149287206, 37.61012333813872, 34.50264296011533, 30.834534678840303, 24.443376581771584, 23.770623097869613, 19.381707512413904, 9.690853756206952, 9.24235143360564, 7.384270382828769, 0.0800897004645202, 57.34091717028084, 50.4443654461429, 48.20476359758265, 48.062566654816926, 30.6078919303235, 28.01279772484892, 26.34198364735158, 26.306434411660156, 20.440810522573766, 10.131532172058302, 10.095982936366868], 'survey_year': [2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011']}